name: CI for project

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Node js app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node js
        uses: actions/setup-node@v3

      - name: Install Dependencies
        uses: npm install

      - name: Build Command
        uses: npm run build
